// Code generated by {{ .AppName }}. DO NOT EDIT.

package {{ .Version }}

// +kubebuilder:object:generate=true

import (
	"k8s.io/apimachinery/pkg/runtime/schema"
	"sigs.k8s.io/controller-runtime/pkg/scheme"
)

var (
	// GroupVersion is group version used to register these objects.
	GroupVersion = schema.GroupVersion{Group: "{{ .Group }}", Version: "{{ .Version }}"}

	// SchemeBuilder is used to add go types to the GroupVersionKind scheme.
	SchemeBuilder = &scheme.Builder{GroupVersion: GroupVersion}

	// AddToScheme adds the types in this group-version to the given scheme.
	AddToScheme = SchemeBuilder.AddToScheme
)

func init() {
	// Register types with the scheme
	{{- range .CRDNames }}
	SchemeBuilder.Register(&{{ .Kind }}{}, &{{ .List }}{})
	{{- end }}
}

